import PropertyCard from "./PropertyCard";

const PropertiesGridContainer = () => {
  return (
    <div className="self-stretch flex flex-row flex-wrap items-start justify-center text-left text-[14.51px] text-gray-700 font-body-regular-600">
      <div className="flex-1 flex flex-row flex-wrap items-start justify-center gap-[8px]">
        <PropertyCard
          propertyImage="/unsplashrlwe8f8anoc@2x.png"
          car="/car.svg"
          bathtub="/bathtub.svg"
          arrowsOut="/arrowsout.svg"
          ellipse1="/ellipse-1@2x.png"
          shareNetwork="/sharenetwork.svg"
          heart="/heart.svg"
          plus="/plus.svg"
        />
        <PropertyCard
          propertyImage="/unsplashrlwe8f8anoc1@2x.png"
          car="/car1.svg"
          bathtub="/bathtub1.svg"
          arrowsOut="/arrowsout.svg"
          ellipse1="/ellipse-1@2x.png"
          shareNetwork="/sharenetwork1.svg"
          heart="/heart1.svg"
          plus="/plus1.svg"
          propWidth="350px"
          propFlex="unset"
          propMinWidth="unset"
          propMaxWidth="unset"
        />
        <PropertyCard
          propertyImage="/unsplashrlwe8f8anoc2@2x.png"
          car="/car2.svg"
          bathtub="/bathtub2.svg"
          arrowsOut="/arrowsout.svg"
          ellipse1="/ellipse-1@2x.png"
          shareNetwork="/sharenetwork.svg"
          heart="/heart.svg"
          plus="/plus.svg"
          propWidth="350px"
          propFlex="unset"
          propMinWidth="unset"
          propMaxWidth="unset"
        />
        <PropertyCard
          propertyImage="/unsplashrlwe8f8anoc3@2x.png"
          car="/car1.svg"
          bathtub="/bathtub1.svg"
          arrowsOut="/arrowsout.svg"
          ellipse1="/ellipse-1@2x.png"
          shareNetwork="/sharenetwork2.svg"
          heart="/heart1.svg"
          plus="/plus2.svg"
          propWidth="350px"
          propFlex="unset"
          propMinWidth="unset"
          propMaxWidth="unset"
        />
        <PropertyCard
          propertyImage="/unsplashrlwe8f8anoc@2x.png"
          car="/car.svg"
          bathtub="/bathtub.svg"
          arrowsOut="/arrowsout.svg"
          ellipse1="/ellipse-1@2x.png"
          shareNetwork="/sharenetwork2.svg"
          heart="/heart2.svg"
          plus="/plus3.svg"
          propWidth="350px"
          propFlex="unset"
          propMinWidth="unset"
          propMaxWidth="unset"
        />
        <PropertyCard
          propertyImage="/unsplashrlwe8f8anoc4@2x.png"
          car="/car3.svg"
          bathtub="/bathtub3.svg"
          arrowsOut="/arrowsout1.svg"
          ellipse1="/ellipse-11@2x.png"
          shareNetwork="/sharenetwork3.svg"
          heart="/heart3.svg"
          plus="/plus4.svg"
          propWidth="350px"
          propFlex="unset"
          propMinWidth="unset"
          propMaxWidth="unset"
        />
        <PropertyCard
          propertyImage="/unsplashrlwe8f8anoc5@2x.png"
          car="/car4.svg"
          bathtub="/bathtub4.svg"
          arrowsOut="/arrowsout1.svg"
          ellipse1="/ellipse-11@2x.png"
          shareNetwork="/sharenetwork4.svg"
          heart="/heart4.svg"
          plus="/plus5.svg"
          propWidth="350px"
          propFlex="unset"
          propMinWidth="unset"
          propMaxWidth="unset"
        />
        <PropertyCard
          propertyImage="/unsplashrlwe8f8anoc6@2x.png"
          car="/car3.svg"
          bathtub="/bathtub3.svg"
          arrowsOut="/arrowsout1.svg"
          ellipse1="/ellipse-11@2x.png"
          shareNetwork="/sharenetwork5.svg"
          heart="/heart3.svg"
          plus="/plus6.svg"
          propWidth="350px"
          propFlex="unset"
          propMinWidth="unset"
          propMaxWidth="unset"
        />
      </div>
    </div>
  );
};

export default PropertiesGridContainer;
